# Fichier Python de frontend/streamlit pour le projet de détection des spoofing hft sur un marché

import streamlit as st 
import requests 
import pandas as pd
import time
import subprocess

# --- CORRECTION POUR STREAMLIT CLOUD ---
# Le cache permet de s'assurer que le serveur n'est lancé qu'une seule fois, 
# même si la page se rafraîchit toutes les secondes.
@st.cache_resource
def start_fastapi():
    try:
        requests.get("http://127.0.0.1:8000/docs", timeout=1)
    except requests.ConnectionError:
        subprocess.Popen(["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "8000"])
        time.sleep(3) # Laisse le temps au serveur de démarrer
    return True

start_fastapi()
# ---------------------------------------

# Configuration de la page
st.set_page_config(page_title="RegTech HFT - Spoofing Detection", layout="wide", page_icon="⚖️")

API_URL = "http://127.0.0.1:8000/api"

# Fonctions utilitaires
def fetch_data(endpoint):
    try:
        response = requests.get(f"{API_URL}/{endpoint}", timeout=1.5)
        if response.status_code == 200:
            return response.json()
        return None
    except requests.exceptions.RequestException:
        return None

def trigger_red_button():
    try:
        requests.post(f"{API_URL}/stress_test/red_button")
        st.toast("🚨 RED BUTTON: Massive HFT attack injected into the queue!")
    except:
        st.error("Unable to reach the server to launch the attack.")

def trigger_reset():
    try:
        requests.post(f"{API_URL}/reset")
        st.toast("🧹 System reset: All data cleared!")
        time.sleep(1)
        st.rerun()
    except:
        st.error("Unable to reach the server for reset.")

st.sidebar.button("🧹 Reset System", type="secondary", on_click=trigger_reset)

# Entête et description de l'application
st.title("⚖️ RegTech Engine - HFT Spoofing Detection")
st.markdown("Real-time market surveillance (Complex Event Processing) using HMM model.")

market_data = fetch_data("market_data")
if not market_data:
    st.error("Backend Server (FastAPI) starting up... Please wait a few seconds and refresh the page.")
    st.stop()

tab_live, tab_compliance = st.tabs(["📈 Live Market (OLTP)", "🚨 Compliance & Alerts (OLAP)"])

# ONGLET 1 : MARCHÉ LIVE (OLTP)
with tab_live:
    st.markdown("### 📊 Real-Time Order Book and Execution Flow")
    
    col1, col2, col3 = st.columns(3)
    current_price = market_data.get("current_price", 100.0)
    volume = market_data.get("daily_volume", 0)
    
    col1.metric("Current Price (CO2)", f"{current_price:.2f} €")
    col2.metric("Traded Volume", f"{volume} lots")
    col3.metric("Network Status", "Smooth (Asynchronous)", "0 ms latency")

    st.divider()
    
    col_bids, col_asks, col_trades = st.columns([1, 1, 1.5])
    
    with col_bids:
        st.subheader("🟩 Buyers (Bids)")
        bids = market_data.get("bids", [])
        if bids:
            st.dataframe(pd.DataFrame(bids), use_container_width=True, hide_index=True)
    
    with col_asks:
        st.subheader("🟥 Sellers (Asks)")
        asks = market_data.get("asks", [])
        if asks:
            st.dataframe(pd.DataFrame(asks), use_container_width=True, hide_index=True)

    with col_trades:
        st.subheader("📜 Latest Validated Transactions")
        history = market_data.get("history", [])
        if history:
            df_history = pd.DataFrame(history)
            st.dataframe(df_history, use_container_width=True, hide_index=True, height=350)


# ONGLET 2 : CONFORMITÉ (OLAP)
with tab_compliance:
    st.markdown("### 👁️ AMF Monitoring - Sliding Window Analysis")
    st.markdown("This section reads alerts generated by the asynchronous engine without slowing down the market.")
    
    col_action, col_alerts = st.columns([1, 3])
    
    with col_action:
        st.button(
            "🔴 Spoofing Attack", 
            type="primary", 
            use_container_width=True, 
            on_click=trigger_red_button
        )
        st.caption("Instantly injects 100 contradictory events into the order book.")
    
    with col_alerts:
        alerts_data = fetch_data("surveillance/alerts")
        if alerts_data and len(alerts_data) > 0:
            st.error(f"⚠️ {len(alerts_data)} malicious entity(ies) detected in RAM!")
            df_alerts = pd.DataFrame(alerts_data)

            st.dataframe(
                df_alerts[["timestamp", "trader_id", "confidence", "ctr_ratio", "reason"]], 
                use_container_width=True, 
                hide_index=True
            )
        else:
            st.success("✅ No suspicious behavior detected. Healthy cancellation/execution ratio.")

# BOUCLE DE RAFRAÎCHISSEMENT TEMPS RÉEL
time.sleep(1)
st.rerun()
